apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: demo-aa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: trial9uvroy.jfrog.io/test-docker/bootstrap:445acaee5e15110416cbd36d314cb690eefe3ac9@sha256:9ef608da9b8e14d95c8c7d3f04cf473214439fd1c5c45ad2bc658562f614f7d3
          name: container-image
